language: node_js
node_js:
  - "6"
  - "7"
  - node # current node version (may be duplicate, but that's OK)
script:
  - npm run prepublish # lint, clean, build (bundles), test (bundles)
branches:
  except:
    - gh-pages
